name: Build and test
on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: mkdir build
      - run: rm -rf build/*
      - run: cp -r dist/* build/
      - run: npm run test:utChartStorage
      - run: npm run test:utgenChartImg -- --verbose
      - run: npm run test:utSortPoints
      - run: npm run test:integration
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-videos
          path: cypress/videos/
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/
